$('#services').bind('pageinit', function(event) {
getServiceList();
});

function getServiceList() {
	
$('#serviceList li').remove();
$('#serviceList').append('<li><a href="http://www.bluesky.co.ls/cardealer.aspx"><img src="images/car.png" width="75" height="75" style="padding-left: 25px;padding-top: 10px;"><img align="right" src="images/arrow.png" width="15" height="30" style="padding: 25px 25px;"><p style="font-size: 18px;padding-left: 25px;"><font face="Open Sans Regular">CAR DEALER</font></p><p style="font-size: 18px;padding-left: 25px;"><font face="Open Sans Regular"">Your personal information, bookings and directions service</font></p></a></li>');
$('#serviceList').append('<li><a href="http://www.bluesky.co.ls/assistant.aspx"><img src="images/assist.png" width="75" height="75" style="padding-left: 25px;padding-top: 10px;" ><img align="right" src="images/arrow.png" width="15" height="30" style="padding: 25px 25px;"><p style="font-size: 18px;padding-left: 25px; "><font face="Open Sans Regular"">ASSISTANT</font></p><p style="font-size: 18px;padding-left: 25px;"><font face="Open Sans Regular"">Telephonic educational study guidelines, assignments, projects and tips for learners</font></p></a></li>');
$('#serviceList').append('<li><a href="http://www.bluesky.co.ls/homework.aspx"><img src="images/teacher.png" width="75" height="75" style="padding-left: 25px;padding-top: 10px;"><img align="right" src="images/arrow.png" width="15" height="30" style="padding: 25px 25px;"><p style="font-size: 18px;padding-left: 25px;"><font face="Open Sans Regular"">TUTOR</font></p><p style="font-size: 18px;padding-left: 25px;"><font face="Open Sans Regular"">Household emergency assistance and dispach of professional suppliers 24/7</font></p></a></li>');
$('#serviceList').append('<li><a href="http://www.bluesky.co.ls/assistanthomeemergency.aspx"><img src="images/home1.png" width="75" height="75" style="padding-left: 25px;padding-top: 10px;"><img align="right" src="images/arrow.png" width="15" height="30" style="padding: 20px 25px;"><p style="font-size: 18px;padding-left: 25px;"><font face="Open Sans Regular"">HOME EMERGENCY</font></p><p style="font-size: 18px;padding-left: 25px;"><font face="Open Sans Regular"">Savings on flights, accomodation, car rentals, local and international holidays</font></p></a></li>');
$('#serviceList').append('<li><a href="http://www.bluesky.co.ls/travel.aspx"><img src="images/travel.png" width="75" height="75" style="padding-left: 25px;padding-top: 10px;;"><img align="right" src="images/arrow.png" width="15" height="30" style="padding: 25px 25px;"><p style="font-size: 18px;padding-left: 25px;"><font face="Open Sans Regular"">TRAVEL</font></p><p style="font-size: 18px;padding-left: 25px;"><font face="Open Sans Regular"">Telephonic and procurement service for electronics, appliences, toys, flowers, jewellery and luggage</font></p></a></li>');
$('#serviceList').append('<li><a href="http://www.bluesky.co.ls/negotiator.aspx"><img src="images/shop.png" width="75" height="75" style="padding-left: 25px;padding-top: 10px;"><img align="right" src="images/arrow.png" width="15" height="30" style="padding: 25px 25px;"><p style="font-size: 18px;padding-left: 25px;"><font face="Open Sans Regular"">SHOPPER</font></p><p style="font-size: 18px;padding-left: 25px;"><font face="Open Sans Regular"">Discount on new and used vehicle tyres, tracking, and accessories</font></p></a></li>');
$('#serviceList').append('<li><a href="https://www.telebuy.co.za/bluesky.co.ls/classifieds.aspx"><img src="images/classifieds.png" width="75" height="75" style="padding-left: 25px;padding-top: 10px;"><img align="right" src="images/arrow.png" width="15" height="30" style="padding: 25px 25px;"><p style="font-size: 18px;padding-left: 25px;"><font face="Open Sans Regular"">CLASSIFIEDS</font></p><p style="font-size: 18px;padding-left: 25px;"><font face="Open Sans Regular"">Free internet based classified advertisement service where you can sell, swap or buy just about anything</font></p></a></li>');
$('#serviceList').append('<li><a href="https://www.telebuy.co.za/bluesky.co.ls/Connect2.aspx"><img src="images/connect.png" width="75" height="75" style="padding-left: 25px;padding-top: 10px;"><img align="right" src="images/arrow.png" width="15" height="30" style="padding: 25px 25px;"><p style="font-size: 18px;padding-left: 25px;"><font face="Open Sans Regular"">CONNECT</font></p><p style="font-size: 18px;padding-left: 25px;"><font face="Open Sans Regular"">Finding the best cellphone and internet connection for you</font></p></a></li>');
$('#serviceList').append('<li><a href="http://www.bluesky.co.ls/funeral.aspx"><img src="images/funeral.png" width="75" height="75" style="padding-left: 25px;padding-top: 10px;"><img align="right" src="images/arrow.png" width="15" height="30" style="padding: 25px 25px;"><p style="font-size: 18px;padding-left: 25px;" ><font face="Open Sans Regular"">FUNERAL ASSIST</font></p><p style="font-size: 18px;padding-left: 25px;"><font face="Open Sans Regular"">Information and assistance with the necessary arrangements such as venue, burial arrangements, catering needs</font></p></a></li>');
$('#serviceList').append('<li><a href="http://www.bluesky.co.ls/healthmedicalmatters.aspx"><img src="images/medical.png" width="75" height="75" style="padding-left: 25px;padding-top: 10px;"><img align="right" src="images/arrow.png" width="15" height="30" style="padding: 25px 25px;"><p style="font-size: 18px;padding-left: 25px;"><font face="Open Sans Regular"">MEDICAL MATTERS</font></p><p style="font-size: 18px;padding-left: 25px;" ><font face="Open Sans Regular"">Instant telephonic access to medical advice from our qualified team of nurses.</font></p></a></li>');
$('#serviceList').append('<li><a href="http://www.bluesky.co.ls/finance.aspx"><img src="images/finance.png" width="75" height="75" style="padding-left: 25px;padding-top: 10px;"><img align="right" src="images/arrow.png" width="15" height="30" style="padding: 25px 25px;"><p style="font-size: 18px;padding-left: 25px;"><font face="Open Sans Regular"">FINANCE ASSIST</font></p><p style="font-size: 18px;padding-left: 25px;"><font face="Open Sans Regular"">Information on current matters, budgeting and telephonic coaching on financial mattere</font></p></a></li>');
$('#serviceList').append('<li><a href="http://www.bluesky.co.ls/legal.aspx"><img src="images/legal.png" width="75" height="75" style="padding-left: 25px;padding-top: 10px;"><img align="right" src="images/arrow.png" width="15" height="30" style="padding: 25px 25px;"><p style="font-size: 18px;padding-left: 25px;"><font face="Open Sans Regular"">LEGAL ASSIST</font></p><p style="font-size: 18px;padding-left: 25px;"><font face="Open Sans Regular"">Information on legal issues and telephonic advice on legal matters such as family and commercial matters</font></p></a></li>');
				
$('#serviceList').listview('refresh');	
}
